from db import Base
from sqlalchemy import Column, Integer, String, Enum
import enum

class MyEnum(str, enum.Enum):
    A = "а"
    B = "б"
    C = "в"
    D = "г"

class MyEnum2(str, enum.Enum):
    A = "а"
    B = "б"
    C = "в"
    D = "г" 
    E = "д"

class Test(Base):
    __tablename__ = "tests"
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    variant = Column(String, unique=True, nullable=False)
    M1 = Column(Enum(MyEnum), nullable=False)
    M2 = Column(Enum(MyEnum), nullable=False)
    M3 = Column(Enum(MyEnum), nullable=False)
    M4 = Column(Enum(MyEnum), nullable=False)
    M5 = Column(Enum(MyEnum), nullable=False)
    M6 = Column(Enum(MyEnum), nullable=False)
    M7 = Column(Enum(MyEnum), nullable=False)
    M8 = Column(Enum(MyEnum), nullable=False)
    M9 = Column(Enum(MyEnum), nullable=False)
    M10 = Column(Enum(MyEnum), nullable=False)
    M11 = Column(Enum(MyEnum), nullable=False)
    M12 = Column(Enum(MyEnum), nullable=False)
    M13 = Column(Enum(MyEnum), nullable=False)
    M14 = Column(Enum(MyEnum), nullable=False)
    M15 = Column(Enum(MyEnum), nullable=False)
    M16 = Column(Enum(MyEnum), nullable=False)
    M17 = Column(Enum(MyEnum), nullable=False)
    M18 = Column(Enum(MyEnum), nullable=False)
    M19 = Column(Enum(MyEnum), nullable=False)
    M20 = Column(Enum(MyEnum), nullable=False)
    M21 = Column(Enum(MyEnum), nullable=False)
    M22 = Column(Enum(MyEnum), nullable=False)
    M23 = Column(Enum(MyEnum), nullable=False)
    M24 = Column(Enum(MyEnum), nullable=False)
    M25 = Column(Enum(MyEnum), nullable=False)
    M26 = Column(Enum(MyEnum), nullable=False)
    M27 = Column(Enum(MyEnum), nullable=False)
    M28 = Column(Enum(MyEnum), nullable=False)
    M29 = Column(Enum(MyEnum), nullable=False)
    M30 = Column(Enum(MyEnum), nullable=False)

    M31 = Column(Enum(MyEnum2), nullable=False)
    M32 = Column(Enum(MyEnum2), nullable=False)
    M33 = Column(Enum(MyEnum2), nullable=False)
    M34 = Column(Enum(MyEnum2), nullable=False)
    M35 = Column(Enum(MyEnum2), nullable=False)
    M36 = Column(Enum(MyEnum2), nullable=False)
    M37 = Column(Enum(MyEnum2), nullable=False)
    M38 = Column(Enum(MyEnum2), nullable=False)
    M39 = Column(Enum(MyEnum2), nullable=False)
    M40 = Column(Enum(MyEnum2), nullable=False)
    M41 = Column(Enum(MyEnum2), nullable=False)
    M42 = Column(Enum(MyEnum2), nullable=False)
    M43 = Column(Enum(MyEnum2), nullable=False)
    M44 = Column(Enum(MyEnum2), nullable=False)
    M45 = Column(Enum(MyEnum2), nullable=False)
    M46 = Column(Enum(MyEnum2), nullable=False)
    M47 = Column(Enum(MyEnum2), nullable=False)
    M48 = Column(Enum(MyEnum2), nullable=False)
    M49 = Column(Enum(MyEnum2), nullable=False)
    M50 = Column(Enum(MyEnum2), nullable=False)
    M51 = Column(Enum(MyEnum2), nullable=False)
    M52 = Column(Enum(MyEnum2), nullable=False)
    M53 = Column(Enum(MyEnum2), nullable=False)
    M54 = Column(Enum(MyEnum2), nullable=False)
    M55 = Column(Enum(MyEnum2), nullable=False)
    M56 = Column(Enum(MyEnum2), nullable=False)
    M57 = Column(Enum(MyEnum2), nullable=False)
    M58 = Column(Enum(MyEnum2), nullable=False)
    M59 = Column(Enum(MyEnum2), nullable=False)
    M60 = Column(Enum(MyEnum2), nullable=False)

    A1 = Column(Enum(MyEnum), nullable=False)
    A2 = Column(Enum(MyEnum), nullable=False)
    A3 = Column(Enum(MyEnum), nullable=False)
    A4 = Column(Enum(MyEnum), nullable=False)
    A5 = Column(Enum(MyEnum), nullable=False)
    A6 = Column(Enum(MyEnum), nullable=False)
    A7 = Column(Enum(MyEnum), nullable=False)
    A8 = Column(Enum(MyEnum), nullable=False)
    A9 = Column(Enum(MyEnum), nullable=False)
    A10 = Column(Enum(MyEnum), nullable=False)
    A11 = Column(Enum(MyEnum), nullable=False)
    A12 = Column(Enum(MyEnum), nullable=False)
    A13 = Column(Enum(MyEnum), nullable=False)
    A14 = Column(Enum(MyEnum), nullable=False)
    A15 = Column(Enum(MyEnum), nullable=False)
    A16 = Column(Enum(MyEnum), nullable=False)
    A17 = Column(Enum(MyEnum), nullable=False)
    A18 = Column(Enum(MyEnum), nullable=False)
    A19 = Column(Enum(MyEnum), nullable=False)
    A20 = Column(Enum(MyEnum), nullable=False)
    A21 = Column(Enum(MyEnum), nullable=False)
    A22 = Column(Enum(MyEnum), nullable=False)
    A23 = Column(Enum(MyEnum), nullable=False)
    A24 = Column(Enum(MyEnum), nullable=False)
    A25 = Column(Enum(MyEnum), nullable=False)
    A26 = Column(Enum(MyEnum), nullable=False)
    A27 = Column(Enum(MyEnum), nullable=False)
    A28 = Column(Enum(MyEnum), nullable=False)
    A29 = Column(Enum(MyEnum), nullable=False)
    A30 = Column(Enum(MyEnum), nullable=False)

    R1 = Column(Enum(MyEnum), nullable=False)
    R2 = Column(Enum(MyEnum), nullable=False)
    R3 = Column(Enum(MyEnum), nullable=False)
    R4 = Column(Enum(MyEnum), nullable=False)
    R5 = Column(Enum(MyEnum), nullable=False)
    R6 = Column(Enum(MyEnum), nullable=False)
    R7 = Column(Enum(MyEnum), nullable=False)
    R8 = Column(Enum(MyEnum), nullable=False)
    R9 = Column(Enum(MyEnum), nullable=False)
    R10 = Column(Enum(MyEnum), nullable=False)
    R11 = Column(Enum(MyEnum), nullable=False)
    R12 = Column(Enum(MyEnum), nullable=False)
    R13 = Column(Enum(MyEnum), nullable=False)
    R14 = Column(Enum(MyEnum), nullable=False)
    R15 = Column(Enum(MyEnum), nullable=False)
    R16 = Column(Enum(MyEnum), nullable=False)
    R17 = Column(Enum(MyEnum), nullable=False)
    R18 = Column(Enum(MyEnum), nullable=False)
    R19 = Column(Enum(MyEnum), nullable=False)
    R20 = Column(Enum(MyEnum), nullable=False)
    R21 = Column(Enum(MyEnum), nullable=False)
    R22 = Column(Enum(MyEnum), nullable=False)
    R23 = Column(Enum(MyEnum), nullable=False)
    R24 = Column(Enum(MyEnum), nullable=False)
    R25 = Column(Enum(MyEnum), nullable=False)
    R26 = Column(Enum(MyEnum), nullable=False)
    R27 = Column(Enum(MyEnum), nullable=False)
    R28 = Column(Enum(MyEnum), nullable=False)
    R29 = Column(Enum(MyEnum), nullable=False)
    R30 = Column(Enum(MyEnum), nullable=False)

    G1 = Column(Enum(MyEnum), nullable=False)
    G2 = Column(Enum(MyEnum), nullable=False)
    G3 = Column(Enum(MyEnum), nullable=False)
    G4 = Column(Enum(MyEnum), nullable=False)
    G5 = Column(Enum(MyEnum), nullable=False)
    G6 = Column(Enum(MyEnum), nullable=False)
    G7 = Column(Enum(MyEnum), nullable=False)
    G8 = Column(Enum(MyEnum), nullable=False)
    G9 = Column(Enum(MyEnum), nullable=False)
    G10 = Column(Enum(MyEnum), nullable=False)
    G11 = Column(Enum(MyEnum), nullable=False)
    G12 = Column(Enum(MyEnum), nullable=False)
    G13 = Column(Enum(MyEnum), nullable=False)
    G14 = Column(Enum(MyEnum), nullable=False)
    G15 = Column(Enum(MyEnum), nullable=False)
    G16 = Column(Enum(MyEnum), nullable=False)
    G17 = Column(Enum(MyEnum), nullable=False)
    G18 = Column(Enum(MyEnum), nullable=False)
    G19 = Column(Enum(MyEnum), nullable=False)
    G20 = Column(Enum(MyEnum), nullable=False)
    G21 = Column(Enum(MyEnum), nullable=False)
    G22 = Column(Enum(MyEnum), nullable=False)
    G23 = Column(Enum(MyEnum), nullable=False)
    G24 = Column(Enum(MyEnum), nullable=False)
    G25 = Column(Enum(MyEnum), nullable=False)
    G26 = Column(Enum(MyEnum), nullable=False)
    G27 = Column(Enum(MyEnum), nullable=False)
    G28 = Column(Enum(MyEnum), nullable=False)
    G29 = Column(Enum(MyEnum), nullable=False)
    G30 = Column(Enum(MyEnum), nullable=False)
    